syntax changes to satisfy FORD
The ford_config.md file is actually a RESOURCE file for FORD.
Ultimately, FORD will run automatically (circleci?) when we make releases.
Presently, we are running FORD locally in a docker container:

cd /Users/thoar/git/DART_development
docker run -it -v `pwd`:/work niemacka/build_ford
cd /work/docs
ford ford_config.md

We are using FORD for our fortran documentation. FORD does not like
doxygen-style comments on the same line as executable statements.
The FORD error is:
Exception: Preceding documentation lines can not be inline

FORD will also throw an exception if there are some Fortran problems.
Exception: END statement outside of any nesting
1) one had a subroutine declaration improperly spelled as 'suboutine'
2) some source codes were snippits, no 'module' declaration
3) some modules just launched into executable statements - no 'contains'
All-in-all amazing that compilers did not complain about some of these.